language: java

jdk:
  - openjdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle


before_script:
  - git fetch
  - git checkout -b gh-pages
  - git merge origin/master
  - git rm --cached --ignore-unmatch index.html
  - chmod +x gradlew

script:


after_script:
