language: java
install: true

jdk:
  - openjdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

before_install:
 - chmod +x gradlew
 
 
before_script:
  - git fetch
  - git checkout -b gh-pages
  - git merge origin/master
  - git rm --cached --ignore-unmatch index.html

script:
  - ./gradlew asciidoctor

after_script:
