language: java
install: true

jdk:
  - openjdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

before_install:
 - chmod +x gradlew
 
 
before_script:
  - git fetch
  - git checkout -b gh-pages
  - git merge origin/master
  - git rm --cached --ignore-unmatch index.html

script:
  - ./gradlew asciidoctor


deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "com.ossez.docs"
  skip_cleanup: true
  local_dir: build
  endpoint: s3.us-east-2.amazonaws.com